title: "Phor3nsic"
description: >-
  Walleson Rodrigues — faith, family, technology, and the bug hunter journey.
baseurl: ""
url: https://wallesonmoura.com.br
domain: wallesonmoura.com.br
twitter_username: ph0r3nisc
github_username:  phor3nsic

markdown: kramdown
lang: en

author:
  name: "Walleson Rodrigues"
  email: "phorensic@pm.me"
