title: "Phor3nsic"
description: >-
  Walleson Rodrigues — ph0r3nsic, hacker, husband, father of three, entrepreneur, and DeepLookLabs founder.
baseurl: ""
url: https://wallesonmoura.com.br
domain: wallesonmoura.com.br
twitter_username: ph0r3nisc
github_username:  phor3nsic

markdown: kramdown
lang: en

supabase_url: "https://zynrjrbosnjsrchrvqjl.supabase.co"
supabase_publishable_key: "sb_publishable_1dpfSDSXmzpFw3sm0JieqA_5YWPP7sS"

author:
  name: "Walleson Rodrigues"
  email: "phorensic@pm.me"
